[csai-ocr-401]
enabled  = true
filter   = csai-ocr-401
logpath  = /var/log/nginx/csai-ocr.access.log
maxretry = 20
findtime = 60
bantime  = 3600
action   = iptables-multiport[name=csai-ocr, port="80,443"]
